CREATE TABLE `s_financial_profits` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `security_code` char(6) NOT NULL COMMENT 'SECURITY_CODE',
  `security_name_abbr` varchar(32) NOT NULL DEFAULT '' COMMENT 'SECURITY_NAME_ABBR',
  `parent_netprofit` double NOT NULL DEFAULT '0' COMMENT '净利润：PARENT_NETPROFIT',
  `total_operate_income` double NOT NULL DEFAULT '0' COMMENT '营业总收入（元）：TOTAL_OPERATE_INCOME',
  `operate_cost` double NOT NULL DEFAULT '0' COMMENT '营业支出：OPERATE_COST',
  `operate_expense` double NOT NULL DEFAULT '0' COMMENT '营业支出：OPERATE_EXPENSE',
  `operate_expense_ratio` double NOT NULL DEFAULT '0' COMMENT '营业支出同比：OPERATE_EXPENSE_RATIO',
  `sale_expense` double NOT NULL DEFAULT '0' COMMENT '销售支出：SALE_EXPENSE',
  `manage_expense` double NOT NULL DEFAULT '0' COMMENT '管理支出：MANAGE_EXPENSE',
  `finance_expense` double NOT NULL DEFAULT '0' COMMENT '财务支出：FINANCE_EXPENSE',
  `total_operate_cost` double NOT NULL DEFAULT '0' COMMENT '营业总支出：TOTAL_OPERATE_COST',
  `operate_profit` double NOT NULL DEFAULT '0' COMMENT '营业利润：OPERATE_PROFIT',
  `income_tax` double NOT NULL DEFAULT '0' COMMENT '退税收入：INCOME_TAX',
  `operate_tax_add` double NOT NULL DEFAULT '0' COMMENT '税收增加：OPERATE_TAX_ADD',
  `total_profit` double NOT NULL DEFAULT '0' COMMENT '利润总额：TOTAL_PROFIT',
  `notice_date` datetime NOT NULL COMMENT '发公告日期，整型格式：NOTICE_DATE',
  `report_date` datetime NOT NULL COMMENT '所属季度，格式为整型，一般为四个季度，20200331,20200631,20200930,20201231',
  `operate_profit_ratio` double NOT NULL DEFAULT '0' COMMENT 'OPERATE_PROFIT_RATIO',
  `deduct_parent_netprofit` double NOT NULL DEFAULT '0' COMMENT 'DE扣非净利润：DUCT_PARENT_NETPROFIT',
  `dpn_ratio` double NOT NULL DEFAULT '0' COMMENT '扣非净利润同比增长：DPN_RATIO',
  PRIMARY KEY (`id`),
  KEY `item_code` (`security_code`),
  KEY `report_date` (`report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='利润表'
