CREATE TABLE `s_financial_statements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `reportdate` datetime NOT NULL COMMENT '所属季度',
  `security_code` char(6) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `security_name_abbr` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `notice_date` datetime NOT NULL COMMENT '公告时间',
  `update_date` datetime NOT NULL COMMENT '更新时间，有的股喜欢更换报表',
  `eitime` datetime DEFAULT NULL,
  `basic_eps` double NOT NULL DEFAULT '0' COMMENT '每股收益（元）：BASIC_EPS',
  `bps` double NOT NULL DEFAULT '0' COMMENT '每股净资产（元）：BPS',
  `weightavg_roe` double NOT NULL DEFAULT '0' COMMENT '净资产收益率：WEIGHTAVG_ROE',
  `mgjyxjje` double NOT NULL DEFAULT '0' COMMENT '每股营业现金流（元）：MGJYXJJE',
  `xsmll` double NOT NULL DEFAULT '0' COMMENT '销售毛利率（%）：XSMLL',
  `ystz` double NOT NULL DEFAULT '0' COMMENT '营业收入同比增长（%）：YSTZ',
  `yshz` double NOT NULL DEFAULT '0' COMMENT '营业收入环比增长（%）：YSHZ',
  `sjltz` double NOT NULL DEFAULT '0' COMMENT '净利润同比增长（%）：SJLTZ',
  `sjlhz` double NOT NULL DEFAULT '0' COMMENT '净利润环比增长（%）：SJLHZ',
  `assigndscrpt` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '分配情况：ASSIGNDSCRPT',
  PRIMARY KEY (`id`),
  KEY `item_code` (`security_code`),
  KEY `report_date` (`reportdate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业绩报表'
